import type {SeaDirectoryItem} from "@/lib/sea-directory";

export const mountainDestinations: SeaDirectoryItem[] = [
  {
    name: "Bansko",
    location: "Pirin Mountains",
    summary: "Best-known mountain base with year-round infrastructure and strong dining depth.",
    facts: ["Large resort ecosystem", "Good for mixed groups", "Reliable transfer routes"],
    image: "https://images.unsplash.com/photo-1749560917112-918847390483?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Bansko mountain resort panorama",
    ratings: {scale: 10, access: 8, affordability: 7, crowdLevel: 7, familyFit: 8, nightlife: 7, walkability: 8},
  },
  {
    name: "Borovets",
    location: "Rila Mountains",
    summary: "Closest major mountain resort to Sofia, ideal for shorter mountain breaks.",
    facts: ["Fast airport transfers", "Compact resort core", "Good first-time mountain trips"],
    image: "https://images.unsplash.com/photo-1708519692028-6e8ae48ea3fc?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Borovets mountain setting with forested slopes",
    ratings: {scale: 10, access: 9, affordability: 6, crowdLevel: 6, familyFit: 8, nightlife: 6, walkability: 8},
  },
  {
    name: "Pamporovo",
    location: "Rhodope Mountains",
    summary: "Softer mountain pace with family-friendly atmosphere and calmer evenings.",
    facts: ["Relaxed rhythm", "Strong family fit", "Scenic forest backdrop"],
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Pamporovo-style mountain landscape",
    ratings: {scale: 10, access: 6, affordability: 8, crowdLevel: 5, familyFit: 9, nightlife: 4, walkability: 7},
  },
  {
    name: "Velingrad",
    location: "Western Rhodope foothills",
    summary: "Spa-town mountain gateway with restorative stays and thermal profile.",
    facts: ["Wellness-heavy offer", "Good shoulder-season value", "Calmer base"],
    image: "https://images.unsplash.com/photo-1590089137678-3d81de766b94?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Wellness-style mountain town atmosphere in Bulgaria",
    ratings: {scale: 10, access: 7, affordability: 7, crowdLevel: 4, familyFit: 8, nightlife: 3, walkability: 7},
  },
  {
    name: "Dobrinishte",
    location: "Near Bansko, Pirin foothills",
    summary: "Lower-key mountain base for travelers prioritizing calm and value.",
    facts: ["Quieter than major hubs", "Good value profile", "Nature-forward pace"],
    image: "https://images.unsplash.com/photo-1708519692028-6e8ae48ea3fc?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Dobrinishte mountain foothills near Bansko",
    ratings: {scale: 10, access: 6, affordability: 8, crowdLevel: 3, familyFit: 7, nightlife: 2, walkability: 6},
  },
  {
    name: "Smolyan",
    location: "Central Rhodope Mountains",
    summary: "Local mountain town base with practical access to southern mountain zones.",
    facts: ["More local atmosphere", "Good for longer stays", "Strong nature proximity"],
    image: "https://images.unsplash.com/photo-1749560917112-918847390483?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Smolyan mountain town landscape in the Rhodopes",
    ratings: {scale: 10, access: 6, affordability: 8, crowdLevel: 4, familyFit: 7, nightlife: 3, walkability: 7},
  },
];

export const mountainHotels: SeaDirectoryItem[] = [
  {
    name: "Kempinski Hotel Grand Arena",
    location: "Bansko",
    destination: "Bansko",
    summary: "Premium mountain stay with high service standards and lift-area convenience.",
    facts: ["Luxury positioning", "Strong spa offer", "Central Bansko access"],
    image: "https://images.unsplash.com/photo-1713714516316-102eafcf4ab3?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Premium mountain hotel base in Bansko",
    hotelRatings: {scale: 10, priceLevel: 4, familyFit: 8, wellness: 9, beachProximity: 9, quietness: 7, nightlifeAccess: 7},
  },
  {
    name: "Premier Luxury Mountain Resort",
    location: "Bansko",
    destination: "Bansko",
    summary: "Upscale option balancing resort comfort with practical access to the mountain core.",
    facts: ["Modern rooms", "Good for couples", "Reliable service profile"],
    image: "https://images.unsplash.com/photo-1713714516195-60224327d751?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Modern mountain hotel in Bansko",
    hotelRatings: {scale: 10, priceLevel: 5, familyFit: 7, wellness: 8, beachProximity: 8, quietness: 8, nightlifeAccess: 6},
  },
  {
    name: "Rila Hotel Borovets",
    location: "Borovets",
    destination: "Borovets",
    summary: "Resort-core hotel with efficient access for short mountain breaks.",
    facts: ["Core location", "Convenient logistics", "Good all-rounder"],
    image: "https://images.unsplash.com/photo-1713714516354-b09dbb1a04b4?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Borovets hotel area near mountain slopes",
    hotelRatings: {scale: 10, priceLevel: 6, familyFit: 8, wellness: 6, beachProximity: 9, quietness: 6, nightlifeAccess: 7},
  },
  {
    name: "Hotel Yastrebets Wellness & Spa",
    location: "Borovets",
    destination: "Borovets",
    summary: "Forest-leaning mountain retreat with spa facilities and quieter positioning.",
    facts: ["Strong wellness profile", "High quietness", "Premium atmosphere"],
    image: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Wellness mountain resort atmosphere in Borovets",
    hotelRatings: {scale: 10, priceLevel: 4, familyFit: 7, wellness: 9, beachProximity: 7, quietness: 9, nightlifeAccess: 4},
  },
  {
    name: "Grand Hotel Murgavets",
    location: "Pamporovo",
    destination: "Pamporovo",
    summary: "Established mountain hotel suited to families and value-minded mountain trips.",
    facts: ["Family-capable", "Good value", "Practical base"],
    image: "https://images.unsplash.com/photo-1713714516316-102eafcf4ab3?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Pamporovo mountain hotel setting",
    hotelRatings: {scale: 10, priceLevel: 7, familyFit: 9, wellness: 6, beachProximity: 8, quietness: 8, nightlifeAccess: 4},
  },
  {
    name: "Perelik Hotel",
    location: "Pamporovo",
    destination: "Pamporovo",
    summary: "Central mountain stay with broad amenities and straightforward resort access.",
    facts: ["Central positioning", "Group-friendly", "Reliable facilities"],
    image: "https://images.unsplash.com/photo-1713714516195-60224327d751?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Mountain hotel in Pamporovo",
    hotelRatings: {scale: 10, priceLevel: 7, familyFit: 8, wellness: 6, beachProximity: 8, quietness: 7, nightlifeAccess: 5},
  },
  {
    name: "Arte Spa & Park Hotel",
    location: "Velingrad",
    destination: "Velingrad",
    summary: "High-comfort spa stay for travelers blending mountain air with wellness focus.",
    facts: ["Strong thermal wellness", "Couples fit", "Polished service"],
    image: "https://images.unsplash.com/photo-1713714516354-b09dbb1a04b4?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Spa-focused mountain hotel in Velingrad",
    hotelRatings: {scale: 10, priceLevel: 5, familyFit: 8, wellness: 10, beachProximity: 7, quietness: 8, nightlifeAccess: 3},
  },
  {
    name: "Spa Club Bor",
    location: "Velingrad",
    destination: "Velingrad",
    summary: "Comfort-led wellness hotel with practical value and easy town access.",
    facts: ["Balanced value", "Wellness amenities", "Easy local access"],
    image: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Velingrad wellness stay in mountain foothills",
    hotelRatings: {scale: 10, priceLevel: 7, familyFit: 7, wellness: 8, beachProximity: 7, quietness: 7, nightlifeAccess: 3},
  },
];
