import type {SeaDirectoryItem} from "@/lib/sea-directory";

export const skiDestinations: SeaDirectoryItem[] = [
  {
    name: "Bansko",
    location: "Pirin Mountains",
    summary: "Largest ski ecosystem in Bulgaria with broad run variety and strong après options.",
    facts: ["Best overall infrastructure", "Large accommodation stock", "Great for mixed skill groups"],
    image: "https://images.unsplash.com/photo-1708519692028-6e8ae48ea3fc?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Ski slope and mountain panorama in Bansko",
    ratings: {scale: 10, access: 8, affordability: 7, crowdLevel: 8, familyFit: 8, nightlife: 8, walkability: 8},
  },
  {
    name: "Borovets",
    location: "Rila Mountains",
    summary: "Closest major ski resort to Sofia, ideal for shorter, logistics-friendly ski trips.",
    facts: ["Fast transfers", "Compact village feel", "Reliable for short breaks"],
    image: "https://images.unsplash.com/photo-1668623851161-d5a4a68ab132?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Ski scene in Borovets, Bulgaria",
    ratings: {scale: 10, access: 9, affordability: 6, crowdLevel: 6, familyFit: 8, nightlife: 6, walkability: 8},
  },
  {
    name: "Pamporovo",
    location: "Rhodope Mountains",
    summary: "Calmer ski base with family-friendly flow and gentler learning environment.",
    facts: ["Beginner-friendly slopes", "Family-oriented", "Lower crowd pressure"],
    image: "https://images.unsplash.com/photo-1616590246052-4332519f9f00?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Rhodope mountain landscape near Pamporovo, Bulgaria",
    ratings: {scale: 10, access: 6, affordability: 8, crowdLevel: 5, familyFit: 9, nightlife: 4, walkability: 7},
  },
  {
    name: "Chepelare",
    location: "Rhodope foothills",
    summary: "Smaller ski-town option for travelers prioritizing value and a local mountain rhythm.",
    facts: ["Quieter mountain town", "Budget-friendly profile", "Good for less crowded trips"],
    image: "https://images.unsplash.com/photo-1649932543297-5394f3a0bd99?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Rhodope forested mountain scene near Chepelare, Bulgaria",
    ratings: {scale: 10, access: 6, affordability: 8, crowdLevel: 4, familyFit: 7, nightlife: 3, walkability: 6},
  },
];

export const skiHotels: SeaDirectoryItem[] = [
  {
    name: "Kempinski Hotel Grand Arena",
    location: "Bansko",
    destination: "Bansko",
    summary: "Premium ski stay with excellent service and lift-area convenience.",
    facts: ["Luxury segment", "Great wellness", "Strong mountain access"],
    hotelRatings: {scale: 10, priceLevel: 4, familyFit: 8, wellness: 9, beachProximity: 9, quietness: 7, nightlifeAccess: 7},
  },
  {
    name: "Lucky Bansko Aparthotel",
    location: "Bansko",
    destination: "Bansko",
    summary: "Well-equipped stay with strong family utility and practical ski-season logistics.",
    facts: ["Family fit", "Good value in segment", "Reliable facilities"],
    hotelRatings: {scale: 10, priceLevel: 6, familyFit: 9, wellness: 8, beachProximity: 8, quietness: 8, nightlifeAccess: 6},
  },
  {
    name: "Rila Hotel Borovets",
    location: "Borovets",
    destination: "Borovets",
    summary: "Resort-core ski hotel ideal for efficient weekend or short ski trips.",
    facts: ["Central base", "Efficient transfers", "Balanced comfort"],
    hotelRatings: {scale: 10, priceLevel: 6, familyFit: 8, wellness: 6, beachProximity: 9, quietness: 6, nightlifeAccess: 7},
  },
  {
    name: "Hotel Yastrebets Wellness & Spa",
    location: "Borovets",
    destination: "Borovets",
    summary: "Forest-edge ski retreat with high quietness and quality spa program.",
    facts: ["Quiet premium option", "Strong wellness", "Couples fit"],
    hotelRatings: {scale: 10, priceLevel: 4, familyFit: 7, wellness: 9, beachProximity: 7, quietness: 9, nightlifeAccess: 4},
  },
  {
    name: "Grand Hotel Murgavets",
    location: "Pamporovo",
    destination: "Pamporovo",
    summary: "Established ski-season hotel with family-friendly profile and good practicality.",
    facts: ["Family-capable", "Value profile", "Reliable access"],
    hotelRatings: {scale: 10, priceLevel: 7, familyFit: 9, wellness: 6, beachProximity: 8, quietness: 8, nightlifeAccess: 4},
  },
  {
    name: "Perelik Hotel",
    location: "Pamporovo",
    destination: "Pamporovo",
    summary: "Central Pamporovo base with broad amenities and easy ski logistics.",
    facts: ["Group friendly", "Convenient location", "Solid all-round stay"],
    hotelRatings: {scale: 10, priceLevel: 7, familyFit: 8, wellness: 6, beachProximity: 8, quietness: 7, nightlifeAccess: 5},
  },
];
