import type {SeaDirectoryItem} from "@/lib/sea-directory";

export const wellnessDestinations: SeaDirectoryItem[] = [
  {
    name: "Velingrad",
    location: "Western Rhodope foothills",
    summary: "Leading spa-town base with strong thermal infrastructure and restorative pace.",
    facts: ["Top wellness profile", "Strong hotel ecosystem", "Great shoulder-season value"],
    image: "https://images.unsplash.com/photo-1590089137678-3d81de766b94?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Velingrad wellness and park atmosphere",
    ratings: {scale: 10, access: 7, affordability: 7, crowdLevel: 4, familyFit: 8, nightlife: 3, walkability: 7},
  },
  {
    name: "Sandanski",
    location: "Southwestern Bulgaria",
    summary: "Mild-climate wellness town suited to slower trips and year-round spa escapes.",
    facts: ["Warm climate profile", "Spa-forward stays", "Calm itinerary fit"],
    image: "https://images.unsplash.com/photo-1633208672767-b798f868c741?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Park and tree-lined atmosphere suitable for Sandanski region stays",
    ratings: {scale: 10, access: 7, affordability: 7, crowdLevel: 4, familyFit: 8, nightlife: 3, walkability: 8},
  },
  {
    name: "Hisarya",
    location: "Plovdiv Province",
    summary: "Historic thermal town with restorative rhythm and manageable crowd levels.",
    facts: ["Thermal heritage", "Calm pace", "Good couples fit"],
    image: "https://images.unsplash.com/photo-1724323697661-a112f7e1eac6?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Park and historic-town atmosphere in the Hisarya region",
    ratings: {scale: 10, access: 8, affordability: 7, crowdLevel: 4, familyFit: 7, nightlife: 2, walkability: 8},
  },
  {
    name: "Devin",
    location: "Rhodope Mountains",
    summary: "Mountain-meets-wellness base for travelers prioritizing nature and recovery.",
    facts: ["Nature-forward stay", "Relaxed rhythm", "Strong value profile"],
    image: "https://images.unsplash.com/photo-1649932544050-94617bcca7d5?auto=format&fit=crop&w=1400&q=85",
    imageAlt: "Rhodope mountain road and forest scenery near Devin",
    ratings: {scale: 10, access: 6, affordability: 8, crowdLevel: 3, familyFit: 7, nightlife: 2, walkability: 7},
  },
];

export const wellnessHotels: SeaDirectoryItem[] = [
  {
    name: "Arte Spa & Park Hotel",
    location: "Velingrad",
    destination: "Velingrad",
    summary: "High-comfort thermal wellness stay with premium spa facilities.",
    facts: ["Top spa profile", "Couples fit", "Refined service"],
    hotelRatings: {scale: 10, priceLevel: 5, familyFit: 8, wellness: 10, beachProximity: 7, quietness: 8, nightlifeAccess: 3},
  },
  {
    name: "Spa Club Bor",
    location: "Velingrad",
    destination: "Velingrad",
    summary: "Comfort-led spa base offering strong value and restorative facilities.",
    facts: ["Balanced value", "Wellness amenities", "Calm atmosphere"],
    hotelRatings: {scale: 10, priceLevel: 7, familyFit: 7, wellness: 8, beachProximity: 7, quietness: 7, nightlifeAccess: 3},
  },
  {
    name: "Interhotel Sandanski",
    location: "Sandanski",
    destination: "Sandanski",
    summary: "Wellness-forward hotel with practical access to spa services and park zones.",
    facts: ["Thermal program", "Central location", "Reliable facilities"],
    hotelRatings: {scale: 10, priceLevel: 6, familyFit: 8, wellness: 9, beachProximity: 8, quietness: 7, nightlifeAccess: 3},
  },
  {
    name: "Kashmir Wellness & Spa Hotel",
    location: "Velingrad",
    destination: "Velingrad",
    summary: "Modern wellness property with upscale comfort and quieter positioning.",
    facts: ["Upscale segment", "Spa-heavy offer", "Quietness"],
    hotelRatings: {scale: 10, priceLevel: 4, familyFit: 7, wellness: 9, beachProximity: 7, quietness: 9, nightlifeAccess: 2},
  },
  {
    name: "Augusta SPA Hotel",
    location: "Hisarya",
    destination: "Hisarya",
    summary: "Thermal town stay with practical wellness offerings and easy walkability.",
    facts: ["Good value", "Thermal profile", "Walkable town context"],
    hotelRatings: {scale: 10, priceLevel: 7, familyFit: 7, wellness: 8, beachProximity: 8, quietness: 8, nightlifeAccess: 2},
  },
  {
    name: "Spa Hotel Ismena",
    location: "Devin",
    destination: "Devin",
    summary: "Nature-near wellness stay suitable for quieter restorative breaks.",
    facts: ["Calm vibe", "Strong quietness", "Good shoulder-season fit"],
    hotelRatings: {scale: 10, priceLevel: 7, familyFit: 7, wellness: 8, beachProximity: 7, quietness: 9, nightlifeAccess: 2},
  },
];
